name: grade checkpoint
on:
  push:
    branches:
      - 'solution'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: action/checkout@v2
        with:
          fetch-depth: 0
      - name: install dependencies
        run: npm i
      - name: run tests
        id: run_tests
        # https://www.npmjs.com/package/jest-cli/v/0.10.0#use---json-for-ci-integrations
        run: |
          TEST=$(npm run test:ci)
          GRADE=${{ fromJSON($TEST).numPassedTests / fromJSON($TEST).numTotalTests }}
          ::set-output name=grade::$($GRADE)
        shell: bash
      - name: send_grade
        # at grade endpoint on remote server validate github.token
        run: |
          curl -X POST https://univ-grade-system-fsa.herokuapp.com/api/grade \
            -H 'Authorization:Bearer ${{ github.token }}' \
            -H 'Content-Type:application/json' \
            -d '{"github_name":"${{ github.actor }}","repository_url":"${{ github.repositoryUrl }}","grade":"${{ steps.run_tests.outputs.grade }}"}'
        shell: bash
