name: grade checkpoint
on:
  push:
    branches:
      - 'solution'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: configure github actions bot
        run: |
          echo "git version is: "; 
          echo $(git --version);
          git config user.name "GitHub Actions Bot";
          git config user.email "<>";
          git show;

      - name: install dependencies
        run: npm i

      - name: jest output to json file
        run: npm run test:ci

      - name: grade tests
        id: grade_tests
        run: |
          num_passed_tests=$(jq '.numPassedTests' testOutput.json)
          num_total_tests=$(jq '.numTotalTests' testOutput.json)
          echo ::set-output name=GRADE::$(echo "scale=3; $num_passed_tests / $num_total_tests" | bc);

      - name: get commit date
        id: commit_date_unix_epoch
        run: echo ::set-output name=DATE::git show -s --format=%ct ${{ github.sha }}

      - name: send grade
        run: |
          echo '{"status":"${{ job.status }}","github_name":"${{ github.actor }}","repository_url":"${{ github.repositoryUrl }}","submitted_at":"${{ env.DATE }}","grade":"${{ env.GRADE }}"}'

          # curl -X POST https://univ-grade-system-fsa.herokuapp.com/api/grade \
          #   -H 'Authorization:Bearer ${{ github.token }}' \
          #   -H 'Content-Type:application/json' \
          #   -d '{"status":"${{ job.status }}","github_name":"${{ github.actor }}","repository_url":"${{ github.repositoryUrl }}","submitted_at":"${{ env.DATE }}","grade":"${{ env.GRADE }}"}'
        env:
          COMMIT_DATE_MS: ${{ steps.commit_date_unix_epoch.outputs.DATE }}
          GRADE: ${{ steps.grade_tests.outputs.GRADE }}
