name: grade checkpoint
on:
  push:
    branches:
      - 'solution'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: npm install
        run: npm i
      - name: jest output to .json
        run: npm run test:ci:grade
      - name: calculate grade
        id: calculate_grade
        run: |
          num_passed_tests=$(jq '.numPassedTests' testOutput.json)
          num_total_tests=$(jq '.numTotalTests' testOutput.json)
          echo ::set-output name=grade::$(echo "scale=3; $num_passed_tests / $num_total_tests" | bc)
      - name: get commit date (unix epoch)
        id: commit_date_unix_epoch
        run: |
          date=$(git show -s --format=%ct ${{ github.sha }})
          echo ::set-output name=date::$date
      - name: generate access token
        id: generate_access_token
        uses: shapirodaniel/gha-jwt@v1.1.0
        with:
          secret: ${{ secrets.GRADE_SECRET }}
          payload: '{"id":"${{ github.actor }}","sha":"${{ github.sha }}"}'
          expiry: '5m'
      - name: send grade
        run: |
          curl -X POST https://univ-grade-system-fsa.herokuapp.com/api/grade \
            -H 'Authorization:Bearer ${{ env.ACCESS_TOKEN }}' \
            -H 'Content-Type:application/json' \
            -d '{"status":"${{ job.status }}","github_name":"${{ github.actor }}","repository_url":"${{ github.repositoryUrl }}","submitted_at":"${{ env.DATE }}","grade":"${{ env.GRADE }}"}'
        env:
          DATE: ${{ steps.commit_date_unix_epoch.outputs.date }}
          GRADE: ${{ steps.calculate_grade.outputs.grade }}
          ACCESS_TOKEN: ${{ steps.generate_access_token.outputs.access_token }}
